// Copyright (c) 2023 Huawei Device Co., Ltd.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Asynchronous `Connector` trait and `HttpConnector` implementation.

mod stream;

use core::future::Future;
use std::io::{Error, ErrorKind};
use std::net::SocketAddr;
use std::str::FromStr;
use std::sync::Arc;

use ylong_http::request::uri::Uri;
#[cfg(feature = "http3")]
use ylong_runtime::net::{ConnectedUdpSocket, UdpSocket};

use crate::async_impl::dns::{DefaultDnsResolver, EyeBallConfig, HappyEyeballs, Resolver};
use crate::runtime::{AsyncRead, AsyncWrite, TcpStream};
use crate::util::config::{ConnectorConfig, HttpVersion};
/// Information of an IO.
use crate::util::ConnInfo;
use crate::{HttpClientError, Timeout};

/// `Connector` trait used by `async_impl::Client`. `Connector` provides
/// asynchronous connection establishment interfaces.
pub trait Connector {
    /// Streams that this connector produces.
    type Stream: AsyncRead + AsyncWrite + ConnInfo + Unpin + Sync + Send + 'static;

    /// Futures generated by this connector when attempting to create a stream.
    type Future: Future<Output = Result<Self::Stream, HttpClientError>>
        + Unpin
        + Sync
        + Send
        + 'static;

    /// Attempts to establish a connection.
    fn connect(&self, uri: &Uri, http_version: HttpVersion) -> Self::Future;
}

/// Connector for creating HTTP or HTTPS connections asynchronously.
///
/// `HttpConnector` implements `async_impl::Connector` trait.
pub struct HttpConnector {
    config: ConnectorConfig,
    resolver: Arc<dyn Resolver>,
}

impl HttpConnector {
    /// Creates a new `HttpConnector` with a `ConnectorConfig`.
    pub(crate) fn new(config: ConnectorConfig, resolver: Arc<dyn Resolver>) -> Self {
        Self { config, resolver }
    }

    /// Creates a new `HttpConnector` with a given dns `Resolver`.
    pub(crate) fn with_dns_resolver<R>(resolver: R) -> Self
    where
        R: Resolver,
    {
        let resolver = Arc::new(resolver) as Arc<dyn Resolver>;
        Self {
            config: Default::default(),
            resolver,
        }
    }
}

impl Default for HttpConnector {
    fn default() -> Self {
        Self {
            config: Default::default(),
            resolver: Arc::new(DefaultDnsResolver::default()),
        }
    }
}

async fn tcp_stream(eyeballs: HappyEyeballs) -> Result<TcpStream, HttpClientError> {
    eyeballs
        .connect()
        .await
        .map_err(|e| {
            #[cfg(target_os = "linux")]
            if format!("{}", e).contains("failed to lookup address information") {
                return HttpClientError::from_dns_error(crate::ErrorKind::Connect, e);
            }
            #[cfg(target_os = "windows")]
            if let Some(code) = e.raw_os_error() {
                if (0x2329..=0x26B2).contains(&code) || code == 0x2AF9 {
                    return HttpClientError::from_dns_error(crate::ErrorKind::Connect, e);
                }
            }
            HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
        })
        .and_then(|stream| match stream.set_nodelay(true) {
            Ok(()) => Ok(stream),
            Err(e) => err_from_io!(Connect, e),
        })
}

async fn dns_query(
    resolver: Arc<dyn Resolver>,
    addr: &str,
) -> Result<Vec<SocketAddr>, HttpClientError> {
    if let Ok(socket_addr) = SocketAddr::from_str(addr) {
        return Ok(vec![socket_addr]);
    }
    let addr_fut = resolver.resolve(addr);
    let socket_addr = addr_fut.await.map_err(|e| {
        HttpClientError::from_dns_error(
            crate::ErrorKind::Connect,
            Error::new(ErrorKind::Interrupted, e),
        )
    })?;
    Ok(socket_addr.collect::<Vec<_>>())
}

async fn eyeballs_connect(
    addrs: Vec<SocketAddr>,
    timeout: Timeout,
) -> Result<TcpStream, HttpClientError> {
    let eyeball_config = EyeBallConfig::new(timeout.inner(), None);
    let happy_eyeballs = HappyEyeballs::new(addrs, eyeball_config);
    tcp_stream(happy_eyeballs).await
}

#[cfg(feature = "http3")]
pub(crate) async fn udp_stream(
    addr: &std::net::SocketAddr,
) -> Result<ConnectedUdpSocket, HttpClientError> {
    let local_addr = match addr {
        std::net::SocketAddr::V4(_) => "0.0.0.0:0",
        std::net::SocketAddr::V6(_) => "[::]:0",
    };
    let sock = UdpSocket::bind(local_addr)
        .await
        .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
    sock.connect(addr)
        .await
        .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))
}

#[cfg(not(feature = "__tls"))]
mod no_tls {
    use core::future::Future;
    use core::pin::Pin;
    use std::time::Instant;

    use ylong_http::request::uri::Uri;

    use super::{eyeballs_connect, Connector, HttpConnector};
    use crate::async_impl::connector::dns_query;
    use crate::async_impl::connector::stream::HttpStream;
    use crate::runtime::TcpStream;
    use crate::util::config::HttpVersion;
    use crate::util::interceptor::ConnProtocol;
    use crate::{ConnData, ConnDetail, HttpClientError, TimeGroup};

    impl Connector for HttpConnector {
        type Stream = HttpStream<TcpStream>;
        type Future =
            Pin<Box<dyn Future<Output = Result<Self::Stream, HttpClientError>> + Sync + Send>>;

        fn connect(&self, uri: &Uri, _http_version: HttpVersion) -> Self::Future {
            // Checks if this uri need be proxied.
            let mut is_proxy = false;
            let mut secure_proxy = false;
            let mut addr = uri.authority().unwrap().to_string();
            if let Some(proxy) = self.config.proxies.match_proxy(uri) {
                let proxy_info = proxy.intercept.proxy_info();
                addr = proxy_info.addr();
                secure_proxy = proxy_info.is_secure();
                is_proxy = true;
            }

            let resolver = self.resolver.clone();
            let timeout = self.config.timeout.clone();
            Box::pin(async move {
                if secure_proxy {
                    return Err(HttpClientError::from_str(
                        crate::ErrorKind::Connect,
                        "HTTPS proxy requires TLS feature",
                    ));
                }
                let mut time_group = TimeGroup::default();
                time_group.set_dns_start(Instant::now());
                let socket_addrs = dns_query(resolver, addr.as_str()).await?;
                time_group.set_dns_end(Instant::now());
                time_group.set_tcp_start(Instant::now());
                let stream = eyeballs_connect(socket_addrs, timeout).await?;
                time_group.set_tcp_end(Instant::now());
                let local = stream
                    .local_addr()
                    .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
                let peer = stream
                    .peer_addr()
                    .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
                let detail = ConnDetail {
                    protocol: ConnProtocol::Tcp,
                    local,
                    peer,
                    addr,
                };

                let data = ConnData::builder()
                    .time_group(time_group)
                    .proxy(is_proxy)
                    .build(detail);
                Ok(HttpStream::new(stream, data))
            })
        }
    }
}

#[cfg(feature = "__tls")]
mod tls {
    use core::future::Future;
    use core::pin::Pin;
    use std::io::{Error, ErrorKind};
    use std::time::Instant;

    use ylong_http::request::uri::{Scheme, Uri};

    use super::{eyeballs_connect, Connector, HttpConnector};
    use crate::async_impl::connector::dns_query;
    use crate::async_impl::connector::stream::HttpStream;
    use crate::async_impl::mix::{MixStream, ProxyStream};
    #[cfg(feature = "http3")]
    use crate::async_impl::quic::QuicConn;
    use crate::async_impl::ssl_stream::AsyncSslStream;
    #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
    use crate::config::FchownConfig;
    use crate::runtime::{AsyncReadExt, AsyncWriteExt, TcpStream};
    use crate::util::config::HttpVersion;
    #[cfg(feature = "http2")]
    use crate::util::information::NegotiateInfo;
    use crate::util::interceptor::ConnProtocol;
    use crate::util::proxy::{
        connect_request, parse_tunnel_response, tunnel_io_error, ProxyInfo, TunnelResponse,
        MAX_TUNNEL_RESPONSE_SIZE,
    };
    use crate::{ConnData, ConnDetail, HttpClientError, TimeGroup, TlsConfig};

    impl Connector for HttpConnector {
        type Stream = HttpStream<MixStream>;
        type Future =
            Pin<Box<dyn Future<Output = Result<Self::Stream, HttpClientError>> + Sync + Send>>;

        fn connect(&self, uri: &Uri, _http_version: HttpVersion) -> Self::Future {
            // Make sure all parts of uri is accurate.
            let proxy_info = self
                .config
                .proxies
                .match_proxy(uri)
                .map(|proxy| proxy.intercept.proxy_info().clone());
            let is_proxy = proxy_info.is_some();
            let addr = proxy_info
                .as_ref()
                .map(ProxyInfo::addr)
                .unwrap_or_else(|| uri.authority().unwrap().to_string());
            #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
            let fchown = self.config.fchown.clone();
            let resolver = self.resolver.clone();
            let timeout = self.config.timeout.clone();
            match *uri.scheme().unwrap() {
                Scheme::HTTP => {
                    let proxy_info = proxy_info.clone();
                    Box::pin(async move {
                        let mut time_group = TimeGroup::default();
                        time_group.set_dns_start(Instant::now());
                        let socket_addrs = dns_query(resolver, addr.as_str()).await?;
                        time_group.set_dns_end(Instant::now());
                        time_group.set_tcp_start(Instant::now());
                        let stream = eyeballs_connect(socket_addrs, timeout).await?;
                        time_group.set_tcp_end(Instant::now());
                        #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
                        if let Some(fchown) = fchown {
                            let _ = stream.fchown(fchown.uid, fchown.gid);
                        }

                        let local = stream.local_addr().map_err(|e| {
                            HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                        })?;
                        let peer = stream.peer_addr().map_err(|e| {
                            HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                        })?;
                        let detail = ConnDetail {
                            protocol: ConnProtocol::Tcp,
                            local,
                            peer,
                            addr: addr.clone(),
                        };
                        let stream = if let Some(proxy_info) = proxy_info {
                            MixStream::Proxy(
                                proxy_connect_stream(stream, &proxy_info, &mut time_group).await?,
                            )
                        } else {
                            MixStream::Http(stream)
                        };
                        let data = ConnData::builder()
                            .time_group(time_group)
                            .proxy(is_proxy)
                            .build(detail);

                        Ok(HttpStream::new(stream, data))
                    })
                }
                Scheme::HTTPS => {
                    let host = uri.host().unwrap().to_string();
                    let port = uri.port().unwrap().as_u16().unwrap();
                    let target_addr = uri.authority().unwrap().to_string();
                    let config = self.config.tls.clone();
                    #[cfg(feature = "http3")]
                    if _http_version == HttpVersion::Http3 {
                        if is_proxy {
                            return Box::pin(async {
                                Err(HttpClientError::from_str(
                                    crate::ErrorKind::Connect,
                                    "HTTP/3 over proxy is not supported",
                                ))
                            });
                        }
                        return Box::pin(async move {
                            let mut time_group = TimeGroup::default();
                            time_group.set_dns_start(Instant::now());
                            let addr_fut = resolver.resolve(&addr);
                            let addrs = addr_fut.await.map_err(|e| {
                                HttpClientError::from_dns_error(
                                    crate::ErrorKind::Connect,
                                    Error::new(ErrorKind::Interrupted, e),
                                )
                            })?;
                            time_group.set_dns_end(Instant::now());
                            time_group.set_quic_start(Instant::now());
                            let mut last_e = None;
                            for addr_it in addrs {
                                let udp_socket = match super::udp_stream(&addr_it).await {
                                    Ok(socket) => socket,
                                    Err(e) => {
                                        last_e = Some(e);
                                        continue;
                                    }
                                };
                                let local = udp_socket.local_addr().map_err(|e| {
                                    HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                                })?;
                                let peer = udp_socket.peer_addr().map_err(|e| {
                                    HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                                })?;
                                let detail = ConnDetail {
                                    protocol: ConnProtocol::Quic,
                                    local,
                                    peer,
                                    addr: addr.clone(),
                                };

                                let mut data = ConnData::builder()
                                    .time_group(time_group.clone())
                                    .proxy(is_proxy)
                                    .build(detail);

                                let mut stream =
                                    HttpStream::new(MixStream::Udp(udp_socket), data.clone());
                                let Ok(quic_conn) =
                                    QuicConn::connect(&mut stream, &config, &host).await
                                else {
                                    continue;
                                };
                                stream.set_quic_conn(quic_conn);
                                data.time_group_mut().set_quic_end(Instant::now());
                                stream.set_conn_data(data);
                                return Ok(stream);
                            }

                            Err(last_e.unwrap_or(HttpClientError::from_str(
                                crate::ErrorKind::Connect,
                                "connect failed",
                            )))
                        });
                    }
                    Box::pin(async move {
                        let mut time_group = TimeGroup::default();
                        time_group.set_dns_start(Instant::now());
                        let socket_addrs = dns_query(resolver, addr.as_str()).await?;
                        time_group.set_dns_end(Instant::now());
                        time_group.set_tcp_start(Instant::now());
                        let stream = eyeballs_connect(socket_addrs, timeout).await?;
                        time_group.set_tcp_end(Instant::now());
                        #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
                        {
                            https_connect(
                                config,
                                addr,
                                target_addr,
                                stream,
                                proxy_info,
                                (host, port),
                                fchown,
                                time_group,
                            )
                            .await
                        }
                        #[cfg(not(all(
                            target_os = "linux",
                            feature = "ylong_base",
                            feature = "__tls"
                        )))]
                        {
                            https_connect(
                                config,
                                addr,
                                target_addr,
                                stream,
                                proxy_info,
                                (host, port),
                                time_group,
                            )
                            .await
                        }
                    })
                }
            }
        }
    }

    async fn https_connect(
        config: TlsConfig,
        addr: String,
        target_addr: String,
        tcp_stream: TcpStream,
        proxy_info: Option<ProxyInfo>,
        (host, port): (String, u16),
        #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))] fchown: Option<
            FchownConfig,
        >,
        mut time_group: TimeGroup,
    ) -> Result<HttpStream<MixStream>, HttpClientError> {
        let is_proxy = proxy_info.is_some();
        let tcp = tcp_stream;
        #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
        if let Some(fchown) = fchown {
            let _ = tcp.fchown(fchown.uid, fchown.gid);
        }
        let local = tcp
            .local_addr()
            .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
        let peer = tcp
            .peer_addr()
            .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;

        let proxy_is_secure = proxy_info
            .as_ref()
            .map(ProxyInfo::is_secure)
            .unwrap_or(false);
        if proxy_info.is_none() || proxy_is_secure {
            time_group.set_tls_start(Instant::now());
        }
        let stream = if let Some(proxy_info) = proxy_info {
            let auth = proxy_info.basic_auth_value();
            let proxy_stream = proxy_connect_stream(tcp, &proxy_info, &mut time_group).await?;
            let tunnel = tunnel(proxy_stream, &host, port, auth)
                .await
                .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
            if !proxy_is_secure {
                time_group.set_tls_start(Instant::now());
            }
            let pinned_key = config.pinning_host_match(target_addr.as_str());
            let mut stream = config
                .ssl_new(&host)
                .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), tunnel, pinned_key))
                .map_err(|e| {
                    HttpClientError::from_tls_error(
                        crate::ErrorKind::Connect,
                        Error::new(ErrorKind::Other, e),
                    )
                })?;
            Pin::new(&mut stream).connect().await.map_err(|e| {
                HttpClientError::from_tls_error(
                    crate::ErrorKind::Connect,
                    Error::new(ErrorKind::Other, e),
                )
            })?;
            HttpsStream::Proxied(stream)
        } else {
            let pinned_key = config.pinning_host_match(target_addr.as_str());
            let mut stream = config
                .ssl_new(&host)
                .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), tcp, pinned_key))
                .map_err(|e| {
                    HttpClientError::from_tls_error(
                        crate::ErrorKind::Connect,
                        Error::new(ErrorKind::Other, e),
                    )
                })?;
            Pin::new(&mut stream).connect().await.map_err(|e| {
                HttpClientError::from_tls_error(
                    crate::ErrorKind::Connect,
                    Error::new(ErrorKind::Other, e),
                )
            })?;
            HttpsStream::Direct(stream)
        };
        time_group.set_tls_end(Instant::now());

        #[cfg(feature = "http2")]
        let alpn = stream.negotiated_alpn_protocol().map(Vec::from);
        let detail = ConnDetail {
            protocol: ConnProtocol::Tcp,
            local,
            peer,
            addr,
        };

        #[cfg(feature = "http2")]
        let data = ConnData::builder()
            .time_group(time_group)
            .proxy(is_proxy)
            .negotiate(NegotiateInfo::from_alpn(alpn))
            .build(detail);

        #[cfg(not(feature = "http2"))]
        let data = ConnData::builder()
            .time_group(time_group)
            .proxy(is_proxy)
            .build(detail);

        let mix = match stream {
            HttpsStream::Direct(stream) => MixStream::Https(stream),
            HttpsStream::Proxied(stream) => MixStream::HttpsOverProxy(stream),
        };

        Ok(HttpStream::new(mix, data))
    }

    enum HttpsStream {
        Direct(AsyncSslStream<TcpStream>),
        Proxied(AsyncSslStream<ProxyStream>),
    }

    impl HttpsStream {
        #[cfg(feature = "http2")]
        fn negotiated_alpn_protocol(&self) -> Option<&[u8]> {
            match self {
                Self::Direct(stream) => stream.negotiated_alpn_protocol(),
                Self::Proxied(stream) => stream.negotiated_alpn_protocol(),
            }
        }
    }

    async fn proxy_connect_stream(
        tcp: TcpStream,
        proxy: &ProxyInfo,
        time_group: &mut TimeGroup,
    ) -> Result<ProxyStream, HttpClientError> {
        if !proxy.is_secure() {
            return Ok(ProxyStream::Tcp(tcp));
        }

        if time_group.tls_start_time().is_none() {
            time_group.set_tls_start(Instant::now());
        }
        let config = proxy.tls_config();
        let mut stream = config
            .ssl_new(proxy.host())
            .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), tcp, None))
            .map_err(|e| {
                HttpClientError::from_tls_error(
                    crate::ErrorKind::Connect,
                    Error::new(ErrorKind::Other, e),
                )
            })?;

        Pin::new(&mut stream).connect().await.map_err(|e| {
            HttpClientError::from_tls_error(
                crate::ErrorKind::Connect,
                Error::new(ErrorKind::Other, e),
            )
        })?;

        if time_group.tls_end_time().is_none() {
            time_group.set_tls_end(Instant::now());
        }
        Ok(ProxyStream::Tls(stream))
    }

    async fn tunnel(
        mut conn: ProxyStream,
        host: &str,
        port: u16,
        auth: Option<String>,
    ) -> Result<ProxyStream, Error> {
        let req = connect_request(host, port, auth.as_deref())?;
        conn.write_all(&req).await?;

        let mut buf = [0; MAX_TUNNEL_RESPONSE_SIZE];
        let mut pos = 0;

        loop {
            let n = conn.read(&mut buf[pos..]).await?;

            if n == 0 {
                return Err(tunnel_io_error(crate::util::proxy::CreateTunnelErr::Unsuccessful));
            }

            pos += n;
            match parse_tunnel_response(&buf[..pos]) {
                Ok(TunnelResponse::Complete) => return Ok(conn),
                Ok(TunnelResponse::Incomplete) => {}
                Err(e) => return Err(tunnel_io_error(e)),
            }
            if pos == buf.len() {
                return Err(tunnel_io_error(
                    crate::util::proxy::CreateTunnelErr::ProxyHeadersTooLong,
                ));
            }
        }
    }

    #[cfg(all(test, feature = "__tls"))]
    mod ut_tunnel_error_debug {
        use crate::util::proxy::CreateTunnelErr;

        /// UT test cases for debug of`CreateTunnelErr`.
        ///
        /// # Brief
        /// 1. Checks `CreateTunnelErr` debug by calling `CreateTunnelErr::fmt`.
        /// 2. Checks if the result is as expected.
        #[test]
        fn ut_tunnel_error_debug_assert() {
            assert_eq!(
                format!("{:?}", CreateTunnelErr::ProxyHeadersTooLong),
                "Proxy headers too long for tunnel"
            );
            assert_eq!(
                format!("{:?}", CreateTunnelErr::ProxyAuthenticationRequired),
                "Proxy authentication required"
            );
            assert_eq!(
                format!("{:?}", CreateTunnelErr::Unsuccessful),
                "Unsuccessful tunnel"
            );
            assert_eq!(
                format!("{}", CreateTunnelErr::ProxyHeadersTooLong),
                "Proxy headers too long for tunnel"
            );
            assert_eq!(
                format!("{}", CreateTunnelErr::ProxyAuthenticationRequired),
                "Proxy authentication required"
            );
            assert_eq!(
                format!("{}", CreateTunnelErr::Unsuccessful),
                "Unsuccessful tunnel"
            );
        }
    }

    #[cfg(all(test, feature = "__tls", feature = "ylong_base"))]
    mod ut_create_tunnel_err_debug {
        use std::net::SocketAddr;
        use std::str::FromStr;

        use ylong_runtime::io::AsyncWriteExt;

        use crate::async_impl::connector::tcp_stream;
        use crate::async_impl::connector::tls::tunnel;
        use crate::async_impl::mix::ProxyStream;
        use crate::async_impl::dns::{EyeBallConfig, HappyEyeballs};
        use crate::start_tcp_server;
        use crate::util::proxy::{tunnel_io_error, CreateTunnelErr};
        use crate::util::test_utils::{format_header_str, TcpHandle};

        /// UT test cases for `tunnel`.
        ///
        /// # Brief
        /// 1. Creates a `tcp stream` by calling `tcp_stream`.
        /// 2. Sends a `Request` by `tunnel`.
        /// 3. Checks if the result is as expected.
        #[test]
        fn ut_ssl_tunnel_error() {
            let mut handles = vec![];
            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
               Shutdown: std::net::Shutdown::Both,
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );

            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    ProxyStream::Tcp(tcp),
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert_eq!(
                    format!("{:?}", res.err()),
                    format!("{:?}", Some(tunnel_io_error(CreateTunnelErr::Unsuccessful)))
                );
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();

            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
               Response: {
                   Status: 407,
                   Version: "HTTP/1.1",
                   Header: "Content-Length", "11",
                   Body: "METHOD GET!",
               },
               Shutdown: std::net::Shutdown::Both,
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );
            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    ProxyStream::Tcp(tcp),
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert_eq!(
                    format!("{:?}", res.err()),
                    format!(
                        "{:?}",
                        Some(tunnel_io_error(CreateTunnelErr::ProxyAuthenticationRequired))
                    )
                );
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();

            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
               Response: {
                   Status: 402,
                   Version: "HTTP/1.1",
                   Header: "Content-Length", "11",
                   Body: "METHOD GET!",
               },
               Shutdown: std::net::Shutdown::Both,
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );
            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    ProxyStream::Tcp(tcp),
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert_eq!(
                    format!("{:?}", res.err()),
                    format!("{:?}", Some(tunnel_io_error(CreateTunnelErr::Unsuccessful)))
                );
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();
        }

        /// UT test cases for `tunnel`.
        ///
        /// # Brief
        /// 1. Creates a `tcp stream` by calling `tcp_stream`.
        /// 2. Sends a `Request` by `tunnel`.
        /// 3. Checks if the result is as expected.
        #[test]
        fn ut_ssl_tunnel_connect() {
            let mut handles = vec![];

            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
                Response: {
                   Status: 200,
                   Version: "HTTP/1.1",
                   Body: "",
               },
               Shutdown: std::net::Shutdown::Both,
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );
            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    ProxyStream::Tcp(tcp),
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert!(res.is_ok());
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();
        }

        /// UT test cases for response beyond size of `tunnel`.
        ///
        /// # Brief
        /// 1. Creates a `tcp stream` by calling `tcp_stream`.
        /// 2. Sends a `Request` by `tunnel`.
        /// 3. Checks if the result is as expected.
        #[test]
        fn ut_ssl_tunnel_resp_beyond_size() {
            let mut handles = vec![];

            let buf = vec![b'b'; 8192];
            let header_value = String::from_utf8(buf).unwrap();

            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
                Response: {
                   Status: 200,
                   Version: "HTTP/1.1",
                   Header: "X-Long", header_value.as_str(),
                   Body: "",
               },
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );
            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    ProxyStream::Tcp(tcp),
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert_eq!(
                    format!("{:?}", res.err()),
                    format!(
                        "{:?}",
                        Some(tunnel_io_error(CreateTunnelErr::ProxyHeadersTooLong))
                    )
                );
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();
        }
    }
}
